name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Download Data
      run: |
        sudo apt install curl unzip
        mkdir data
        curl -LO https://github.com/AakashKumarNain/CaptchaCracker/raw/master/captcha_images_v2.zip
        unzip -qq captcha_images_v2.zip -d data
        rm captcha_images_v2.zip 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install -e .

    - name: Train Model
      run: |
        python src/dev/train.py -ep 3 -d greedy

    - name: Publish image to Docker Hub
      uses: elgohr/Publish-Docker-Github-Action@master
      with: 
        name: lequan2902/captcha_ctc
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Dockerfile

